### ISSUE TITLE
Apple can't check for malicious software …

### ISSUE THREAD

**Issue by bourbens** [dennis-tra/alfred-dict.cc-workflow#11]
Dear Dennis,

I use your workflow on a daily basis - thank you so much for having provided it!

Today I tried to install the workflow on a new machine and I have encountered a new problem: 

"dictcc_arm64" can't be opened
because Apple cannot check it
for malicious software.
This software needs to be updated.
Contact the developer for more
information."

Do you have any notion what this could entail? The debugger doesn't show anything. I'm on Alfred 5 btw. 

Kind regards,
Ben

**Comment by dennis-tra** [comment]
Hi @bourbens, thanks for the kind words!

Could you try the steps described in the [`Permissions`](https://github.com/dennis-tra/alfred-dict.cc-workflow#permissions) section of the readme?

Let me know if you have already done that and it's still not working :/

Cheers,
Dennis

**Comment by bourbens** [comment]
It worked!!! Fantastic. Thank you very much Dennis!
