### ISSUE TITLE
Universal Action doesn't send selected Text

### ISSUE THREAD

**Issue by gogamid** [dennis-tra/alfred-dict.cc-workflow#18]
Universal Action Shortcut just opens Alfred Action without text, example:
<img width="720" alt="image" src="https://github.com/dennis-tra/alfred-dict.cc-workflow/assets/36050790/562d220f-4b97-49ee-8153-81058286e287">
is this expected?

I have Mac M1 with Sonoma 14.2.1, installed new release and assigned shortcut to Universal Action

**Comment by dennis-tra** [comment]
Hi @gogamid, this is not what I would expect. I'm also on a Mac M1 with Sonoma 14.2.1. For me, when I select text and press the Universal Action shortcut:

<img width="1292" alt="image" src="https://github.com/dennis-tra/alfred-dict.cc-workflow/assets/11836793/a740df82-e638-45a4-b951-2d0d64bf1d6b">


it opens Alfred but the text isn't populated:

<img width="724" alt="Screenshot 2024-01-05 at 10 04 18" src="https://github.com/dennis-tra/alfred-dict.cc-workflow/assets/11836793/85140ee8-63ac-4016-aba8-6b6f39b954f7">

However when I select "Translate", the text is properly forwarded to the workflow:

<img width="724" alt="image" src="https://github.com/dennis-tra/alfred-dict.cc-workflow/assets/11836793/404b7adf-5bec-45a3-b600-d680c72a5983">

This sounds more like an issue in Alfred itself than this workflow 🤔

**Comment by gogamid** [comment]
this is clear and it works -> but it is a long way...

**Comment by gogamid** [comment]
Selected Text -> Hotkey -> Translate {Selected Text} works now. The issue was about Permissions: https://www.alfredapp.com/help/getting-started/permissions/
I had to revoke and grant again...
