### ISSUE TITLE
Customized default languages

### ISSUE THREAD

**Issue by GoOz** [dennis-tra/alfred-dict.cc-workflow#4]
Hey there!

Great workflow, but I think it could be even better if we could define different default languages than `ger` and `en` by using Workflow Environment Variables I guess.

For example, I search mostly for fr<->en translations but I still have to type `dict en fr` or `dict fr en` all the time. :/

**Comment by dennis-tra** [comment]
Hey @GoOz ,

This would certainly a good addition!

I see what I can do the next days.

Will let you know ;)

**Comment by dennis-tra** [comment]
@GoOz I just released a new version. 

Have a look at the readme for configuration instructions - let me know if that works for you ;)

**Comment by GoOz** [comment]
This is perfect! Thank you very much 🙏
