### ISSUE TITLE
Alfred 3 compactibility

### ISSUE THREAD

**Issue by Robis74** [dennis-tra/alfred-dict.cc-workflow#5]
Hi, 

seems that it's not compatible with Alfred 3 anymore?

Best, 
Rob

**Comment by dennis-tra** [comment]
Hi @Robis74 ,

sorry for the late reply - I didn't have notifications enabled for this repo - now I'm watching all activity.

I have actually moved to Alfred 4 a while ago and just exported the workflow from there. I can imagine that this is not compatible with Alfred 3 anymore.

As I haven't changed much of the code and was using Alfred 3 before it should still be possible to get it to run, but I'm currently not able to get an Alfred 3 installation. I'd need some help here, so if anyone is interested I could explain the steps.

If you're not interested in the default-language-feature it may be fine to just download an older release? Maybe [v1.0.1](https://github.com/dennis-tra/alfred-dict.cc-workflow/releases/tag/v1.0.1) works for you?

Best,
Dennis

**Comment by MBischof-gcx** [comment]
@dennis-tra I think this issue can be closed with a reference to this issue:
https://github.com/dennis-tra/alfred-dict.cc-workflow/issues/9
