### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by dennis-tra** [dennis-tra/alfred-dict.cc-workflow#8]
An issue to discuss problems associated with version 2.0.0

**Comment by svenjacobs** [comment]
Seems to work fine so far, thank you 👍🏼

**Comment by natterstefan** [comment]
I can confirm that as well. 👍  Thanks, @dennis-tra!

**Comment by dennis-tra** [comment]
Did you have to explicitly give execute-permissions to the binaries?

**Comment by natterstefan** [comment]
> Did you have to explicitly give execute-permissions to the binaries?

Yes, I had to.

**Comment by sven-s** [comment]
Works fine for me (M1 Pro). I needed to grant the permissions.

**Comment by muffix** [comment]
Clearing the extended file attributes before installing the workflow into Alfred worked for me. `xattr -c ~/Downloads/Dict.cc.alfredworkflow` clears all of them, but just removing `com.apple.quarantine` would probably have sufficed.

**Comment by svenjacobs** [comment]
> However, when searching for `foo`, I get the following error:

I'm getting the same error. It seems to happen for **some** words that start with `fo`. For instance `foot` is also affected. However `for` or `four` work 🤷🏼‍♂️

**Comment by josefschoeggl** [comment]
Thanks a lot for the quick update, it works again!

**Comment by dennis-tra** [comment]
Hi @depressiveRobot, thanks for reporting!

I found the problem and will release another RC in a couple of minutes 👍

---

On another note, thanks so much to everybody who "bought me a coffee" the last couple of days :) ☕️ it really makes my day every time I receive the email notification :)

**Comment by svenjacobs** [comment]
I found another minor issue with RC3. It seems that single quotes are escaped in the output:

<img width="740" alt="Screenshot 2022-03-28 at 08 41 34" src="https://user-images.githubusercontent.com/255313/160340855-bba76377-509b-412f-92f5-467a82530183.png">

**Comment by dennis-tra** [comment]
@svenjacobs thanks for reporting and generally the feedback you're providing :)

I have fixed it and will release another RC today. Right now I'm just string replacing `\'` by `'`. Not very elegant but it works. There might be other escaped characters but I haven't come across any - so I'll go with that "solution" for now.

While I was at it I've also added a new alternative action to the search results. When you hold `⌘` or `⌥` and then press enter the browser opens `dict.cc` with your query :)

**Comment by dennis-tra** [comment]
Alright, I'm using the workflow for a week now and it seems to be working fine 🎉

@sven-s You mentioned in the other issue https://github.com/dennis-tra/alfred-dict.cc-workflow/issues/7 you could sign the binary? I'm not very familiar with the process and only have done it once with https://github.com/mitchellh/gon. If it's not too much of hassle for you I would really appreciate you could sign the current binaries of rc-4. If you don't have time for that I'll just release the current ones on Wednesday :)

**Comment by sven-s** [comment]
I am also not familiar with the process, since I only developed iOS Apps for customers, but I will look at the process this evening and and the tool you mentioned. It is always fun to learn something new ;-)

**Comment by dennis-tra** [comment]
Hi everyone, thanks for the help! Yesterday, I finally released the new version:

https://github.com/dennis-tra/alfred-dict.cc-workflow/releases/tag/2.0.0

I'll close this issue, but feel free to open new ones if anything comes up.

---

@sven-s I figured that the workflow on the release page can just be exchanged if we come around notarizing the included binaries :)

**Comment by sven-s** [comment]
@dennis-tra yesterday I started to look into the gon stuff and managed to sign a binary. Today I will try to notarize it.
